<?php

function webform_copy_value_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == "webform_component_edit_form") {
    $type = $form['type']['#value'];
    if(in_array($type, array('textfield','select'))){
      $node = $form['#node'];
      $nid = $node->nid;
      $fieldList = get_webform_fields_by_type($nid, $type);
      unset($fieldList[$form['cid']['#value']]);
      array_unshift($fieldList, '-None-');

      $form['value']['#disabled'] =  TRUE;
      $form['copy_value_of'] = array (
        '#type' => 'select',
        '#title' => 'Copy value of field',
        '#options' => $fieldList,
        '#default_value' => NULL,
        '#weight' => 0,
      );
      array_unshift($form['#submit'], 'webform_copy_value_submit');
    }
  }
  if(strpos($form_id, 'webform_client_form') !== FALSE) {
    $sourceTargetMap = get_source_target_field_map($form['#node']->nid);

    if(!empty($sourceTargetMap)) {
      $scm = array();
      foreach($sourceTargetMap as $k => $val) {
        $target = str_replace('_', '-', $val['target']);
        $source = str_replace('_', '-', $val['source']);
        $scm[$source][$val['cid']] = $target;
      }

      // Attach necessary JavaScript.
      $form['#attached']['js'][] = drupal_get_path('module', 'webform_copy_value') . '/js/webform_copy_value.js';
      $form['#attached']['js'][] = array (
        // Pass PHP variables to Drupal.settings.
        'data' => array(
          'sourceTargetMap' => $scm,
        ),
        'type' => 'setting',
      );
    }
  }
  dsm($form);
  dsm($form_state['values']);
}

function webform_copy_value_submit($form, &$form_state) {
  $sourceFieldId = $form_state['values']['copy_value_of'];
  if($sourceFieldId != 0) {
    $sourceFormKey = $form['#node']->webform['components'][$sourceFieldId]['form_key'];
    $form_state['values']['value'] = '[webform_copy_value:' . $sourceFormKey . ']';
  }
}

function get_source_target_field_map($nid) {
  $query = "SELECT cid, form_key, value from webform_component WHERE nid = {$nid} AND  value LIKE '%webform_copy_value:%'";
  $results = db_query($query);
  $sourceTargetMap = array();
  $count = 0;
  foreach ($results->fetchAll() as $result) {
    $sourceTargetMap[$count]['cid'] = $result->cid;
    $sourceTargetMap[$count]['target'] = $result->form_key;
    
    $sourceField = preg_match('/\[webform_copy_value\:(.*?)\]/', $result->value, $match);
    
    $sourceTargetMap[$count]['source'] = $match[1];
    
    $count++;
  }
  
  return $sourceTargetMap;
}

function get_webform_fields_by_type($nid, $type) {
  $query = "SELECT cid, form_key from webform_component WHERE nid = {$nid} and type = '{$type}'";
  $results = db_query($query);
  $fields = array();

  foreach ($results->fetchAll() as $result) {
    $cid  = $result->cid;
    $fields[$cid] = $result->form_key;
  }

  return $fields;
}

